@host=http://localhost:5250

### Get all patients
GET {{host}}/Patients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYWEwYjQ3Mi1mNDhiLTRmNzMtYjBkOC01OWQ3NjFiOTQ3YTkiLCJnaXZlbl9uYW1lIjoiZmlyc3QgbmFtZSIsImZhbWlseV9uYW1lIjoibGFzdCBuYW1lIiwicm9sZSI6IkRvY3RvciIsImV4cCI6MTY4OTg2NDQ0NiwiaXNzIjoiZG9jdG9yLWFwcG9pbnRtZW50LWJvb2tpbmctc3lzdGVtIn0.QvO5WzMcrIJ5VkJRdQr7-PMM0-LL92r-vGiO1zR8gBQ


### Create a new patient
POST {{host}}/Patients
Content-Type: application/json

{
    "FirstName" : "123",
    "LastName" : "Patient"
}