@host=http://localhost:5250

### Get all slots
GET {{host}}/Slots
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYWEwYjQ3Mi1mNDhiLTRmNzMtYjBkOC01OWQ3NjFiOTQ3YTkiLCJnaXZlbl9uYW1lIjoiZmlyc3QgbmFtZSIsImZhbWlseV9uYW1lIjoibGFzdCBuYW1lIiwicm9sZSI6IkRvY3RvciIsImV4cCI6MTY4OTg2NDQ0NiwiaXNzIjoiZG9jdG9yLWFwcG9pbnRtZW50LWJvb2tpbmctc3lzdGVtIn0.QvO5WzMcrIJ5VkJRdQr7-PMM0-LL92r-vGiO1zR8gBQ

### Get available slots
GET {{host}}/Slots/available
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYWEwYjQ3Mi1mNDhiLTRmNzMtYjBkOC01OWQ3NjFiOTQ3YTkiLCJnaXZlbl9uYW1lIjoiZmlyc3QgbmFtZSIsImZhbWlseV9uYW1lIjoibGFzdCBuYW1lIiwicm9sZSI6IkRvY3RvciIsImV4cCI6MTY4OTg2NDQ0NiwiaXNzIjoiZG9jdG9yLWFwcG9pbnRtZW50LWJvb2tpbmctc3lzdGVtIn0.QvO5WzMcrIJ5VkJRdQr7-PMM0-LL92r-vGiO1zR8gBQ

### Create a new slot
POST {{host}}/Slots
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYWEwYjQ3Mi1mNDhiLTRmNzMtYjBkOC01OWQ3NjFiOTQ3YTkiLCJnaXZlbl9uYW1lIjoiZmlyc3QgbmFtZSIsImZhbWlseV9uYW1lIjoibGFzdCBuYW1lIiwicm9sZSI6IkRvY3RvciIsImV4cCI6MTY4OTg2NDQ0NiwiaXNzIjoiZG9jdG9yLWFwcG9pbnRtZW50LWJvb2tpbmctc3lzdGVtIn0.QvO5WzMcrIJ5VkJRdQr7-PMM0-LL92r-vGiO1zR8gBQ
Content-Type: application/json

{
    "StartDate": "2023-07-18T10:00:00",
    "DoctorName": "doctor Y",
    "IsReserved": false,
    "Cost": 56.782
}