@host=http://localhost:5250

GET {{host}}/Slots

###

GET {{host}}/Slots/available

###

POST {{host}}/Slots
Content-Type: application/json

{
    "StartDate": "2023-11-10T00:00:00",
    "DoctorName": "doctor Y",
    "IsReserved": true,
    "Cost": 56.782
}